### ISSUE TITLE
How do I add?

### ISSUE THREAD

**Issue by Mr4sR** [kessec/SAMPAHK#18]
How do I add another function for samp.ahk?

**Comment by mookums** [comment]
You add it like you would any other AHK function. If you wish to contribute to the project, follow the naming conventions as detailed below.

- Place your memory addresses and offsets at the top of the file.
- Place your functions in the appropriate section in the file.
- Add your functions to the index inside the SAMP.ahk file. (Be sure to add annotations.)
- Add an increment to the version following Semantic 2.0.
- Make a pull request.

**Comment by Mr4sR** [comment]
@mistermuki have discord ?

**Comment by mookums** [comment]
mister muki#7878
